version: "3.0.0-alpha.36"
slug: hamh
name: Home-Assistant-Matter-Hub
description: Publish your entities from Home Assistant to any Matter-compatible controller like Alexa, Apple Home or Google Home.
url: https://github.com/t0bst4r/home-assistant-matter-hub
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
webui: http://[HOST]:[PORT:8482]/
map:
  - addon_config:rw
options:
  app_log_level: info
  disable_log_colors: false
  web_port: 8482
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|warn|error)
  disable_log_colors: bool
  web_port: int(1,)
  mdns_network_interface: "str?"
